language: python
python:
    - 2.6
    - 2.7
env:
    - BUILDENV=lucid
    - BUILDENV=precise
    - BUILDENV=latest
install:
    - pip install --use-mirrors -r .travis/requirements-$BUILDENV.txt
script:
    - trial scrapy scrapyd
notifications:
    - irc:
        - "irc.freenode.org#scrapy"
